on:
  schedule:
    - cron:  '48 */6 * * *'

name: Figures Update

jobs:
  render:
    name: Figures Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Install font on ubuntu
        run: |
          apt-get update
          apt-get install -y --no-install-recommends
            fonts-ipaexfont

      - uses: actions/cache@v1
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('renv'); renv::restore(confirm = FALSE)"
      - name: 
        run: |
          Rscript -e 'source("mapping.R")'

      - name: Commit results
        run: |
          git add figures/*
          git commit figures/* -m 'Update' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"